services:
  - type: web
    name: rockwood-studio
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: FORMSPREE_ENDPOINT
        sync: false
